# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Dec  7 14:37:41 2020
# ------------------------------------------------

package:
    name: libffi
    version: '3.3'
source:
    sha256: 3f2f86094f5cf4c36cfe850d2fe029d01f5c2c2296619407c8ba0d8207da9a6b
    url: https://github.com/libffi/libffi/archive/v3.3.tar.gz
build:
    number: '2'
    run_exports:
        - libffi >=3.3,<4.0a0
    string: h046ec9c_2
requirements:
    build:
        - autoconf 2.69 pl5320hbcb3906_10
        - automake 1.16.2 pl5320h694c41f_3
        - cctools_osx-64 949.0.1 h2f0f38f_18
        - clang 11.0.0 h694c41f_2
        - clang-11 11.0.0 default_h9e6edd0_2
        - clang_osx-64 11.0.0 hb91bd55_8
        - clangxx 11.0.0 default_h9e6edd0_2
        - clangxx_osx-64 11.0.0 h7e1b574_8
        - compiler-rt 11.0.0 h01488ec_2
        - compiler-rt_osx-64 11.0.0 hd3c4e95_2
        - ld64_osx-64 530 hea264c1_18
        - ldid 2.1.2 h7660a38_2
        - libclang-cpp11 11.0.0 default_h9e6edd0_2
        - libcxx 11.0.0 h4c3b8ed_1
        - libiconv 1.16 haf1e3a3_0
        - libllvm11 11.0.0 hf85e3d2_0
        - libtool 2.4.6 h2e338ed_1007
        - llvm-tools 11.0.0 hf85e3d2_0
        - m4 1.4.18 haf1e3a3_1001
        - make 4.3 h22f3db7_1
        - patch 2.7.6 haf1e3a3_1001
        - perl 5.26.2 hbcb3906_1008
        - tapi 1100.0.11 h9ce4665_0
        - texinfo 6.7 pl526h1b7e3c9_1
        - zlib 1.2.11 h7795811_1010
    host:
        - libcxx 11.0.0 h4c3b8ed_1
    run:
        - libcxx >=11.0.0
test:
    commands:
        - test -e $PREFIX/lib/libffi${SHLIB_EXT}
        - test -e $PREFIX/lib/libffi.a
        - test -e $PREFIX/include/ffi.h
        - test -e $PREFIX/include/ffitarget.h
    requires: null
about:
    description: 'The libffi library provides a portable, high level programming interface

        to various calling conventions. This allows a programmer to call any

        function specified by a call interface description at run-time.

        '
    dev_url: https://github.com/libffi/libffi
    doc_url: https://sourceware.org/libffi/
    home: https://sourceware.org/libffi/
    license: MIT
    license_file: LICENSE
    summary: A Portable Foreign Function Interface Library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - isuruf
        - scopatz
        - stefan-balke
