# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Jan  8 05:29:12 2021
# ------------------------------------------------

package:
    name: setuptools
    version: 49.6.0
source:
    patches:
        - 0001-Remove-exact-pinning-on-certifi-and-wincertstore.patch
        - 0002-disable-downloads-inside-conda-build.patch
    sha256: 0f56c19057bf062124144788fdcbe7685dc0fb506da0acf1540189ce95111813
    url: https://github.com/pypa/setuptools/archive/v49.6.0.tar.gz
build:
    entry_points:
        - easy_install = setuptools.command.easy_install:main
    number: '3'
    string: py39h6e9494a_3
requirements:
    build: []
    host:
        - ca-certificates 2020.12.5 h033912b_0
        - certifi 2020.12.5 py39h6e9494a_1
        - libcxx 11.0.0 h4c3b8ed_1
        - libffi 3.3 h046ec9c_2
        - ncurses 6.2 h2e338ed_4
        - openssl 1.1.1i h35c211d_0
        - python 3.9.1 h1d169a7_2_cpython
        - python_abi 3.9 1_cp39
        - readline 8.0 h0678c8f_2
        - sqlite 3.34.0 h17101e1_0
        - tk 8.6.10 h0419947_1
        - tzdata 2020f he74cb21_0
        - xz 5.2.5 haf1e3a3_1
        - zlib 1.2.11 h7795811_1010
    run:
        - certifi >=2016.9.26
        - python >=3.9,<3.10.0a0
        - python_abi 3.9.* *_cp39
test:
    commands:
        - easy_install --help
    imports:
        - easy_install
        - pkg_resources
        - setuptools
about:
    description: 'Setuptools is a fully-featured, actively-maintained, and stable
        library

        designed to facilitate packaging Python projects.

        '
    dev_url: https://github.com/pypa/setuptools
    doc_source_url: https://github.com/pypa/setuptools/tree/master/docs
    doc_url: http://pythonhosted.org/setuptools/
    home: https://github.com/pypa/setuptools
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Download, build, install, upgrade, and uninstall Python packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - nicoddemus
        - ocefpaf
