CI: azure
CONDA_BUILD_SYSROOT: /Applications/Xcode_11.7.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
MACOSX_DEPLOYMENT_TARGET: '10.9'
c_compiler: '*'
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: '*'
extend_keys:
- ignore_version
- ignore_build_only_deps
- extend_keys
- pin_run_as_build
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
lua: '5'
macos_machine: x86_64-apple-darwin13.4.0
numpy: '1.11'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: '2.7'
python_abi_tag: cp39
python_impl: cpython
python_impl_version: '3.9'
python_version: '3.9'
r_base: '3.5'
target_platform: osx-64
vc: '*'
zip_keys:
- - python_abi_tag
  - python_version
  - python_impl_version
  - python_impl
