# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Oct 14 10:03:45 2020
# ------------------------------------------------

package:
    name: zlib
    version: 1.2.11
source:
    sha256: c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1
    url: http://zlib.net/zlib-1.2.11.tar.gz
build:
    number: '1010'
    run_exports:
        - zlib >=1.2.11,<1.3.0a0
    string: h7795811_1010
requirements:
    build:
        - clang_bootstrap_osx-64 10.0.1 h05bbb7f_10
        - make 4.3 h0b31af3_0
test:
    commands:
        - test -f ${PREFIX}/lib/libz.a
about:
    description: 'zlib is designed to be a free, general-purpose, lossless data-compression

        library for use on virtually any computer hardware and operating system.

        '
    dev_url: https://github.com/madler/zlib
    doc_url: http://zlib.net/manual.html
    home: http://zlib.net/
    license: Zlib
    license_family: Other
    license_file: license.txt
    summary: Massively spiffy yet delicately unobtrusive compression library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - groutr
        - mingwandroid
        - msarahan
        - ocefpaf
