# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sat Dec  5 22:43:07 2020
# ------------------------------------------------

package:
    name: ca-certificates
    version: 2020.12.5
source:
    sha256: 1a4995114262bffbc2413b159f2a1a480c969de6e6eb13ee966d470af86af59c
    url: https://pypi.io/packages/source/c/certifi/certifi-2020.12.5.tar.gz
build:
    number: '0'
    string: h033912b_0
requirements:
    build: []
    run: []
test:
    commands:
        - test -f "${PREFIX}/ssl/cacert.pem"
        - test -f "${PREFIX}/ssl/cert.pem"
        - curl --cacert "${PREFIX}/ssl/cacert.pem" https://www.google.com
    requires:
        - curl
about:
    home: https://github.com/conda-forge/ca-certificates-feedstock
    license: ISC
    license_file: LICENSE
    summary: Certificates for use with other packages.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
