# This file created by conda-build 3.20.5
# ------------------------------------------------

package:
    name: openssl
    version: 1.1.1i
source:
    patches:
        - 0001-Don-t-use-USE_BCRYPTGENRANDOM-for-VS-older-than-2015.patch
    sha256: e8be6a35fe41d10603c3cc635e93289ed00bf34b79671a3a4de64fcee00d5242
    url: http://www.openssl.org/source/openssl-1.1.1i.tar.gz
build:
    no_link: lib/libcrypto.1.1.dylib
    number: 0
    run_exports:
        - openssl >=1.1.1i,<1.1.2a
    string: h35c211d_0
requirements:
    build:
        - cctools_osx-64 949.0.1 h2f0f38f_18
        - clang 11.0.0 h694c41f_2
        - clang-11 11.0.0 default_h9e6edd0_2
        - clang_osx-64 11.0.0 hb91bd55_8
        - clangxx 11.0.0 default_h9e6edd0_2
        - compiler-rt 11.0.0 h01488ec_2
        - compiler-rt_osx-64 11.0.0 hd3c4e95_2
        - ld64_osx-64 530 hea264c1_18
        - ldid 2.1.2 h7660a38_2
        - libclang-cpp11 11.0.0 default_h9e6edd0_2
        - libcxx 11.0.0 h4c3b8ed_1
        - libllvm11 11.0.0 hf85e3d2_0
        - llvm-tools 11.0.0 hf85e3d2_0
        - make 4.3 h22f3db7_1
        - perl 5.26.2 hbcb3906_1008
        - tapi 1100.0.11 h9ce4665_0
        - zlib 1.2.11 h7795811_1010
    run:
        - ca-certificates
test:
    commands:
        - touch checksum.txt
        - openssl sha256 checksum.txt
about:
    dev_url: https://github.com/openssl/openssl
    doc_url: https://www.openssl.org/docs/man1.1.1/
    home: http://www.openssl.org/
    license: OpenSSL
    license_family: Apache
    license_file: LICENSE
    summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - carlodri
        - jakirkham
        - jjhelmus
        - msarahan
        - ocefpaf
        - pelson
