CI: azure
CONDA_BUILD_SYSROOT: /Applications/Xcode_12.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk
MACOSX_DEPLOYMENT_TARGET: '10.9'
MACOSX_SDK_VERSION: '11.0'
bzip2: '1'
c_compiler: clang
c_compiler_version: '11'
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: clangxx
cxx_compiler_version: '11'
extend_keys:
- ignore_version
- ignore_build_only_deps
- pin_run_as_build
- extend_keys
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
libffi: '3.3'
lua: '5'
macos_machine: x86_64-apple-darwin13.4.0
ncurses: '6.2'
numpy: '1.16'
openssl: 1.1.1
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  bzip2:
    max_pin: x
  libffi:
    max_pin: x.x
  ncurses:
    max_pin: x.x
  openssl:
    max_pin: x.x.x
  readline:
    max_pin: x
  sqlite:
    max_pin: x
  tk:
    max_pin: x.x
  xz:
    max_pin: x.x
  zlib:
    max_pin: x.x
python: '3.9'
python_impl: cpython
r_base: '3.5'
readline: '8.0'
sqlite: '3'
target_platform: osx-64
tk: '8.6'
xz: '5.2'
zip_keys:
- - c_compiler_version
  - cxx_compiler_version
zlib: '1.2'
