# This file created by conda-build 3.21.4
# ------------------------------------------------

package:
  name: python
  version: 3.9.1
source:
  - md5: 61981498e75ac8f00adcb908281fadb6
    patches:
      - patches/0000-Fix-off-by-one-error-in-_winapi_WaitForMultipleObjec.patch
      - patches/0001-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
      - patches/0002-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - patches/0003-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
      - patches/0004-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
      - patches/0005-Support-cross-compiling-byte-code.patch
      - patches/0006-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
      - patches/0007-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
      - patches/0008-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - patches/0009-Win32-Do-not-download-externals.patch
      - patches/0010-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
      - patches/0011-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0012-Disable-new-dtags-in-unixccompiler.py.patch
      - patches/0013-Fix-cross-compilation-on-Debian-based-distros.patch
      - patches/0014-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
      - patches/0015-Unvendor-openssl.patch
      - patches/0016-Unvendor-sqlite3.patch
      - patches/0017-venv-Revert-a-change-from-https-github.com-python-cp.patch
      - patches/0018-Win-Add-back-the-DLLSuffix-used-to-find-the-openssl-.patch
      - patches/0019-Use-ranlib-from-env-if-env-variable-is-set.patch
      - patches/0020-Add-CondaEcosystemModifyDllSearchPath.patch
      - patches/0021-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
      - patches/0022-Doing-d1trimfile.patch
      - patches/0023-egg-debugging-with-Windows-debug-builds.patch
      - patches/0024-Add-CONDA_DLL_SEARCH_MODIFICATION_KEEP_GIL-to-aid-de.patch
      - patches/0025-cross-compile-darwin.patch
      - patches/0032-Fix-TZPATH-on-windows.patch
      - patches/0033-gh24324.patch
    url: https://www.python.org/ftp/python/3.9.1/Python-3.9.1.tar.xz
build:
  activate_in_script: true
  detect_binary_files_with_prefix: true
  ignore_run_exports:
    - bzip2
    - clangxx_osx-64
  no_link: null
  number: 5
  run_exports:
    noarch:
      - python
    weak:
      - python_abi 3.9.* *_cp39
  script_env:
    - CONDA_FORGE=yes
    - PY_INTERP_DEBUG=no
    - PY_INTERP_LINKAGE_NATURE=static
  skip_compile_pyc: null
  string: h2502468_5_cpython
requirements:
  build:
    - cctools_osx-64 949.0.1 h2f0f38f_19
    - clang 11.0.1 h694c41f_1
    - clang-11 11.0.1 default_hf8bb9ca_1
    - clang_osx-64 11.0.1 hb91bd55_0
    - clangxx 11.0.1 default_hf8bb9ca_1
    - clangxx_osx-64 11.0.1 h7e1b574_0
    - compiler-rt 11.0.1 h654b07c_0
    - compiler-rt_osx-64 11.0.1 h8c5fa43_0
    - ld64_osx-64 530 hea264c1_19
    - ldid 2.1.2 h7660a38_2
    - libclang-cpp11 11.0.1 default_hf8bb9ca_1
    - libcxx 11.0.1 habf9029_0
    - libiconv 1.16 haf1e3a3_0
    - libllvm11 11.0.1 h223d4b2_0
    - libtool 2.4.6 h2e338ed_1007
    - llvm-tools 11.0.1 h223d4b2_0
    - make 4.3 h22f3db7_1
    - pkg-config 0.29.2 h31203cd_1008
    - tapi 1100.0.11 h9ce4665_0
    - zlib 1.2.11 h7795811_1010
  host:
    - bzip2 1.0.8 hc929b4f_4
    - ca-certificates 2020.12.5 h033912b_0
    - libcxx 11.0.1 habf9029_0
    - libffi 3.3 h046ec9c_2
    - ncurses 6.2 h2e338ed_4
    - openssl 1.1.1i h35c211d_0
    - readline 8.0 h0678c8f_2
    - sqlite 3.34.0 h17101e1_0
    - tk 8.6.10 h0419947_1
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.11 h7795811_1010
  run:
    - libcxx >=11.0.1
    - libffi >=3.3,<3.4.0a0
    - ncurses >=6.2,<6.3.0a0
    - ncurses >=6.2,<6.3.0a0
    - openssl >=1.1.1i,<1.1.2a
    - readline >=8.0,<9.0a0
    - sqlite >=3.34.0,<4.0a0
    - tk >=8.6.10,<8.7.0a0
    - tzdata
    - xz >=5.2.5,<5.3.0a0
    - zlib >=1.2.11,<1.3.0a0
  run_constrained:
    - python_abi 3.9.* *_cp39
test:
  commands:
    - python -V
    - python3 -V
    - 2to3 -h
    - pydoc -h
    - python3-config --help
    - python -c "from zoneinfo import ZoneInfo; from datetime import datetime; dt
      = datetime(2020, 10, 31, 12, tzinfo=ZoneInfo('America/Los_Angeles')); print(dt.tzname())"
    - python -m venv test-venv
    - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    - for f in ${CONDA_PREFIX}/lib/python*/_sysconfig*.py; do echo "Checking $f:";
      if [[ `rg @ $f` ]]; then echo "FAILED ON $f"; cat $f; exit 1; fi; done
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.a
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.nolto.a
    - pushd tests
    - pushd distutils
    - python setup.py install -v -v
    - python -c "import foobar"
    - popd
    - pushd prefix-replacement
    - bash build-and-test.sh
    - popd
    - pushd cmake
    - cmake -GNinja -DPY_VER=3.9.1
    - popd
    - popd
    - test ! -f default.profraw
  downstreams:
    - cython
    - setuptools
  files:
    - tests/cmake/*
    - tests/cython/*
    - tests/distutils/*
    - tests/prefix-replacement/*
  requires:
    - clang_osx-64 11.*
    - clangxx_osx-64 11.*
    - cmake
    - ninja
    - ripgrep
about:
  description: 'Python is a widely used high-level, general-purpose, interpreted,
    dynamic

    programming language. Its design philosophy emphasizes code

    readability, and its syntax allows programmers to express concepts in

    fewer lines of code than would be possible in languages such as C++ or

    Java. The language provides constructs intended to enable clear programs

    on both a small and large scale.

    '
  dev_url: https://docs.python.org/devguide/
  doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
  doc_url: https://www.python.org/doc/versions/
  home: https://www.python.org/
  license: Python-2.0
  license_file: LICENSE
  summary: General purpose programming language
extra:
  copy_test_source_files: true
  feedstock-name: python
  final: true
  recipe-maintainers:
    - isuruf
    - jakirkham
    - mbargull
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
