# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Aug 12 05:06:41 2020
# ------------------------------------------------

package:
    name: xz
    version: 5.2.5
source:
    patches:
        - 0001-Add-vs2008-support-via-cmake.patch
        - 0002-Add-gettimeofday-for-VS2008.patch
    sha256: 5117f930900b341493827d63aa910ff5e011e0b994197c3b71c08a20228a42df
    url: http://downloads.sourceforge.net/project/lzmautils/xz-5.2.5.tar.bz2
build:
    number: '1'
    run_exports:
        - xz >=5.2.5,<6.0a0
    string: haf1e3a3_1
requirements:
    build:
        - autoconf 2.69 pl526h1de35cc_9
        - automake 1.16.2 pl526_1
        - cctools_osx-64 949.0.1 h5ba7a2e_4
        - clang 10.0.1 default_hf57f61e_1
        - clang_osx-64 10.0.1 h05bbb7f_6
        - clangxx 10.0.1 default_hf57f61e_1
        - compiler-rt 10.0.1 he6db49b_0
        - compiler-rt_osx-64 10.0.1 h033240e_0
        - ld64_osx-64 530 h3c32e8a_4
        - libclang-cpp10 10.0.1 default_hf57f61e_1
        - libcxx 10.0.1 h5f48129_0
        - libllvm10 10.0.1 h009f743_1
        - libtool 2.4.6 haf1e3a3_1003
        - llvm-tools 10.0.1 h1341992_1
        - m4 1.4.18 h1de35cc_1001
        - make 4.3 h0b31af3_0
        - perl 5.26.2 haec8ef5_1006
        - tapi 1000.10.8 h879752b_4
        - zlib 1.2.11 1007
about:
    description: 'XZ Utils is free general-purpose data compression software with
        a high

        compression ratio. XZ Utils were written for POSIX-like systems, but also

        work on some not-so-POSIX systems.

        '
    dev_url: http://git.tukaani.org/
    doc_source_url: https://github.com/xz-mirror/xz/blob/master/README
    doc_url: http://tukaani.org/xz/
    home: http://tukaani.org/xz/
    license: LGPL-2.1 and GPL-2.0
    license_file: COPYING
    summary: Data compression software with high compression ratio
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mingwandroid
        - msarahan
        - nehaljwani
        - ocefpaf
        - scopatz
