CI: azure
CONDA_BUILD_SYSROOT: /Applications/Xcode_12.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
MACOSX_DEPLOYMENT_TARGET: '10.9'
c_compiler: clang
c_compiler_version: '11'
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: clangxx
extend_keys:
- pin_run_as_build
- ignore_build_only_deps
- ignore_version
- extend_keys
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
lua: '5'
macos_machine: x86_64-apple-darwin13.4.0
ncurses: '6.2'
numpy: '1.11'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  ncurses:
    max_pin: x.x
  readline:
    max_pin: x
  zlib:
    max_pin: x.x
python: '3.8'
r_base: '3.5'
readline: '8.0'
target_platform: osx-64
zlib: '1.2'
