# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Dec  2 12:19:36 2020
# ------------------------------------------------

package:
    name: sqlite
    version: 3.34.0
source:
    patches: null
    sha256: bf6db7fae37d51754737747aaaf413b4d6b3b5fbacd52bdb2d0d6e5b2edd9aee
    url: https://www.sqlite.org/2020/sqlite-autoconf-3340000.tar.gz
build:
    number: '0'
    run_exports:
        - sqlite >=3.34.0,<4.0a0
    string: h17101e1_0
requirements:
    build:
        - cctools_osx-64 949.0.1 h8e49ea9_16
        - clang 11.0.0 h694c41f_2
        - clang-11 11.0.0 default_h9e6edd0_2
        - clang_osx-64 11.0.0 hb91bd55_7
        - clangxx 11.0.0 default_h9e6edd0_2
        - compiler-rt 11.0.0 h01488ec_2
        - compiler-rt_osx-64 11.0.0 hd3c4e95_2
        - ld64_osx-64 530 h66d9e41_16
        - ldid 2.1.2 h7660a38_2
        - libclang-cpp11 11.0.0 default_h9e6edd0_2
        - libcxx 11.0.0 h4c3b8ed_1
        - libllvm11 11.0.0 hf85e3d2_0
        - libtool 2.4.6 h2e338ed_1007
        - llvm-tools 11.0.0 hf85e3d2_0
        - make 4.3 h22f3db7_1
        - tapi 1100.0.11 h9ce4665_0
        - zlib 1.2.11 h7795811_1010
    host:
        - ncurses 6.2 h2e338ed_4
        - readline 8.0 h0678c8f_2
        - zlib 1.2.11 h7795811_1010
    run:
        - ncurses >=6.2,<6.3.0a0
        - ncurses >=6.2,<6.3.0a0
        - readline >=8.0,<9.0a0
        - readline >=8.0,<9.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - sqlite3 --version
        - test -f $PREFIX/lib/libsqlite3${SHLIB_EXT}
        - test ! -f $PREFIX/lib/libsqlite3.a
        - test -f $PREFIX/include/sqlite3.h
        - test -f $PREFIX/include/sqlite3ext.h
about:
    description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

        public-domain, SQL database engine.It is the most used database engine

        in the world.

        '
    dev_url: https://github.com/mackyle/sqlite
    doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
    doc_url: http://www.sqlite.org/docs.html
    home: http://www.sqlite.org/
    license: Public-Domain (http://www.sqlite.org/copyright.html)
    license_url: http://www.sqlite.org/copyright.html
    summary: Implements a self-contained, zero-configuration, SQL database engine
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - snorfalorpagus
        - xylar
