# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Jan  6 23:22:58 2021
# ------------------------------------------------

package:
    name: certifi
    version: 2020.12.5
source:
    -   folder: certifi
        sha256: 1a4995114262bffbc2413b159f2a1a480c969de6e6eb13ee966d470af86af59c
        url: https://pypi.io/packages/source/c/certifi/certifi-2020.12.5.tar.gz
    -   folder: pip_wheel
        sha256: 0f35d63b7245205f4060efe1982f5ea2196aa6e5b26c07669adcf800e2542026
        url: https://pypi.io/packages/py2.py3/p/pip/pip-20.2.3-py2.py3-none-any.whl
    -   folder: setuptools_wheel
        sha256: 4dd5bb0a0a0cff77b46ca5dd3a84857ee48c83e8223886b556613c724994073f
        url: https://pypi.io/packages/py3/s/setuptools/setuptools-49.6.0-py3-none-any.whl
build:
    number: '1'
    string: py39h6e9494a_1
requirements:
    build: []
    host:
        - ca-certificates 2020.12.5 h033912b_0
        - libcxx 11.0.0 h4c3b8ed_1
        - libffi 3.3 h046ec9c_2
        - ncurses 6.2 h2e338ed_4
        - openssl 1.1.1i h35c211d_0
        - python 3.9.1 h1d169a7_2_cpython
        - readline 8.0 h0678c8f_2
        - sqlite 3.34.0 h17101e1_0
        - tk 8.6.10 h0419947_1
        - tzdata 2020f he74cb21_0
        - xz 5.2.5 haf1e3a3_1
        - zlib 1.2.11 h7795811_1010
    run:
        - python >=3.9,<3.10.0a0
        - python_abi 3.9.* *_cp39
test:
    imports:
        - certifi
about:
    description: 'Certifi is a curated collection of Root Certificates for validating
        the

        trustworthiness of SSL certificates while verifying the identity of TLS

        hosts.

        '
    dev_url: https://github.com/certifi/python-certifi
    doc_source_url: https://github.com/certifi/certifi.io/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/certifi
    home: http://certifi.io/
    license: ISC
    license_file: certifi/LICENSE
    summary: Python package for providing Mozilla's CA Bundle.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - ocefpaf
        - pelson
        - sigmavirus24
