CI: azure
CONDA_BUILD_SYSROOT: /Applications/Xcode_12.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
MACOSX_DEPLOYMENT_TARGET: '10.9'
MACOSX_SDK_VERSION: '10.12'
c_compiler: clang_bootstrap
c_compiler_version: 10.0.0
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: clang_bootstrap
cxx_compiler_version: 10.0.0
dummy_var: '0'
extend_keys:
- pin_run_as_build
- ignore_version
- extend_keys
- ignore_build_only_deps
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
lua: '5'
macos_machine: x86_64-apple-darwin13.4.0
numpy: '1.16'
openturns: '1.16'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  openturns:
    max_pin: x.x
python: '3.8'
r_base: '3.5'
target_platform: osx-64
vc: '14'
