# This file created by conda-build 3.21.4
# ------------------------------------------------

package:
  name: libcxx
  version: 11.0.1
source:
  - patches:
      - libcxx_10.9_compatibility.patch
      - libcxxabi_10.9_compatibility.diff
    sha256: af95d00f833dd67114b21c3cfe72dff2e1cdab627651f977b087a837136d653b
    url: https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.1/llvm-project-11.0.1.src.tar.xz
build:
  ignore_run_exports:
    - libstdcxx-ng
  missing_dso_whitelist:
    - /usr/lib/libc++abi.dylib
  noarch: false
  noarch_python: false
  number: '0'
  string: habf9029_0
requirements:
  build: []
  run: []
test:
  commands:
    - echo 0
    - test -f $PREFIX/include/c++/v1/iterator
    - bash compile_test.sh
    - if [ -f $PREFIX/lib/libc++abi.dylib ]; then exit 1; fi
  downstreams:
    - libcxx-testing
    - openturns
    - python-symengine
  files:
    - compile_test.sh
    - test_sources
  requires:
    - cctools
    - clang
    - clangxx
    - ld64
    - llvm-tools
about:
  home: http://llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  license_family: Apache
  license_file: libcxx/LICENSE.TXT
  summary: LLVM C++ standard library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - SylvainCorlay
    - beckermr
    - inducer
    - isuruf
    - jakirkham
    - timsnyder
