# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Oct  7 14:01:14 2020
# ------------------------------------------------

package:
    name: tk
    version: 8.6.10
source:
    -   folder: tcl8.6.10
        sha256: 5196dbf6638e3df8d5c87b5815c8c2b758496eb6f0e41446596c9a4e638d87ed
        url: https://downloads.sourceforge.net/tcl/tcl8.6.10-src.tar.gz
    -   folder: tk8.6.10
        sha256: 63df418a859d0a463347f95ded5cd88a3dd3aaa1ceecaeee362194bc30f3e386
        url: https://downloads.sourceforge.net/tcl/tk8.6.10-src.tar.gz
build:
    detect_binary_files_with_prefix: true
    number: '1'
    run_exports:
        - tk >=8.6.10,<8.7.0a0
    string: hb0a8c7a_1
requirements:
    build:
        - cctools_osx-64 949.0.1 h5ba7a2e_7
        - clang 10.0.1 default_hf57f61e_1
        - clang_osx-64 10.0.1 h05bbb7f_10
        - clangxx 10.0.1 default_hf57f61e_1
        - compiler-rt 10.0.1 he6db49b_0
        - compiler-rt_osx-64 10.0.1 h033240e_0
        - ld64_osx-64 530 h3c32e8a_7
        - libclang-cpp10 10.0.1 default_hf57f61e_1
        - libcxx 10.0.1 h5f48129_0
        - libllvm10 10.0.1 h009f743_3
        - llvm-tools 10.0.1 h1341992_3
        - tapi 1000.10.8 h879752b_4
        - zlib 1.2.11 h7795811_1009
    host:
        - zlib 1.2.11 h7795811_1009
    run:
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -f "${PREFIX}/bin/tclsh"
        - test -f "${PREFIX}/bin/wish"
        - test -f "${PREFIX}/bin/tclsh8.6"
        - test -f "${PREFIX}/bin/wish8.6"
        - test -f "${PREFIX}/include/tcl.h"
        - test -f "${PREFIX}/include/tclDecls.h"
        - test -f "${PREFIX}/include/tclPlatDecls.h"
        - test -f "${PREFIX}/include/tclPlatDecls.h"
        - test -f "${PREFIX}/include/tclTomMathDecls.h"
        - test -f "${PREFIX}/include/tclTomMath.h"
        - test -f "${PREFIX}/include/tk.h"
        - test -f "${PREFIX}/include/tkDecls.h"
        - test -f "${PREFIX}/include/tkPlatDecls.h"
        - test -f "${PREFIX}/lib/libtcl8.6.dylib"
        - test -f "${PREFIX}/lib/libtclstub8.6.a"
        - test -f "${PREFIX}/lib/libtk8.6.dylib"
        - test -f "${PREFIX}/lib/libtkstub8.6.a"
        - tclsh hello.tcl
        - tclsh8.6 hello.tcl
        - wish hello.tcl
        - wish8.6 hello.tcl
    files:
        - hello.tcl
about:
    home: http://www.tcl.tk/
    license: TCL
    license_family: BSD
    license_file: tcl8.6.10/license.terms
    summary: A dynamic programming language with GUI support.  Bundles Tcl and Tk.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
